lib/mindfull_web/router.ex
defmodule MindfullWeb.Router do
  use MindfullWeb, :router

  import MindfullWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MindfullWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # remove when configured mail server
  # if Mix.env == :dev do
  forward "/sent_emails", Bamboo.SentEmailViewerPlug
  # end

  scope "/", MindfullWeb do
    pipe_through :browser

    live "/", PageLive, :index

    scope "/classroom" do
      live "/list", Classroom.ListLive, :list
      pipe_through [:require_authenticated_user]
      live "/new", Classroom.NewLive, :new
      live "/:id", Classroom.ShowLive, :show
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", MindfullWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: MindfullWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", MindfullWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", MindfullWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings/update_password", UserSettingsController, :update_password
    put "/users/settings/update_email", UserSettingsController, :update_email
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", MindfullWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/mindfull_web/views/layout_view.ex
defmodule MindfullWeb.LayoutView do
  use MindfullWeb, :view
end

lib/mindfull_web/templates/layout/_menu.html.eex
<%= link "All classrooms", to: Routes.list_path(@conn, :list), class: "px-6 py-3 font-bold uppercase text-secondary hover:text-primary" %>
<%= if @current_user do %>
  <%= link "New classroom", to: Routes.new_path(@conn, :new), class: "px-6 py-3 font-bold uppercase text-secondary hover:text-primary" %>
  <%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete , class: "px-6 py-3 font-bold uppercase text-secondary hover:text-primary" %>
<% else %>
  <%= link "New classroom", to: Routes.new_path(@conn, :new), class: "px-6 py-3 font-bold uppercase text-secondary hover:text-primary" %>
  <%= link "Register", to: Routes.user_registration_path(@conn, :new), class: "px-6 py-3 font-bold uppercase text-secondary hover:text-primary" %>
  <%= link "Log in", to: Routes.user_session_path(@conn, :new), class: "px-6 py-3 font-bold uppercase text-secondary hover:text-primary" %>
<% end %>

lib/mindfull_web/templates/layout/_user_menu.html.eex
<%= if @current_user do %>
    <%= link @current_user.email, to: Routes.user_settings_path(@conn, :edit), class: "float-right px-6 py-3 font-bold uppercase text-secondary hover:text-primary" %>
<% end %>

lib/mindfull_web/templates/layout/app.html.eex
<main>
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/mindfull_web/templates/layout/live.html.leex
<main>
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/mindfull_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Mindfull", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <link href="https://fonts.googleapis.com/css?family=Titillium+Web:400,400i,600,600i,700&display=swap" rel="stylesheet">
    <style>
      [x-cloak] {
          display: none !important;
          visibility: hidden;
      }
    </style>
  </head>
  <body class="min-h-screen font-custom" x-data="{ aside: false }" x-cloak>
    <header class="top-0 left-0 right-0 z-10 px-6 py-4">
      <div class="container mx-auto">
        <%= render "_user_menu.html", assigns %>
        <div class="flex items-center">
          <button class="text-secondary lg:hidden" x-on:click.prevent="aside = !aside">
            <svg class="w-6 h-6 current-fill" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                                                                                                                                               viewBox="-49 141 512 512" style="enable-background:new -49 141 512 512;" xml:space="preserve">
              <g>
              <g>
              <path d="M413,422H1c-13.807,0-25-11.193-25-25s11.193-25,25-25h412c13.807,0,25,11.193,25,25S426.807,422,413,422z"/>
              </g>
              <g>
              <path d="M413,562H1c-13.807,0-25-11.193-25-25s11.193-25,25-25h412c13.807,0,25,11.193,25,25S426.807,562,413,562z"/>
              </g>
              <g>
              <path d="M413,282H1c-13.807,0-25-11.193-25-25s11.193-25,25-25h412c13.807,0,25,11.193,25,25S426.807,282,413,282z"/>
              </g>
              </g>
            </svg>

          </button>
          <nav class="items-center hidden lg:flex">
            <a href="/" class="px-6 py-3 font-bold uppercase border-b-2 text-primary border-primary">Home</a>
            <%= render "_menu.html", assigns %>
          </nav>
        </div>

      </div>
    </header>
    <main>
       <div
            x-show="aside"
            x-transition:enter="transition ease-out duration-200"
            x-transition:enter-start="opacity-0"
            x-transition:enter-end="opacity-100"
            x-transition:leave="transition ease-in duration-200"
            x-transition:leave-start="opacity-100"
            x-transition:leave-end="opacity-0"
            class="fixed inset-0 z-40 w-screen h-screen lg:hidden">
             <div class="fixed inset-0 z-40 bg-black opacity-75" x-on:click.prevent="aside = false"></div>
      </div>


       <aside class="lg:hidden" x-bind:class="{ 'visible': aside }">
          <img src="/images/logo.jpeg" class="h-40 mx-auto lg:h-8">
          <div class="menu" class="ml-10">
            <a href="<%= Routes.list_path(@conn, :list) %>" class="px-6 py-3 ml-5 font-bold uppercase link text-secondary hover:text-primary">
                  <span class="font-light tracking-tighter text">All classrooms</span>
              </a>
            <%= if @current_user do %>
              <a href="<%= Routes.list_path(@conn, :list) %>" class="px-6 py-3 ml-5 font-bold uppercase link text-secondary hover:text-primary">
                  <span class="font-light tracking-tighter text">All classrooms</span>
              </a>
              <a href="<%= Routes.user_session_path(@conn, :delete) %>" class="px-6 py-3 ml-5 font-bold uppercase link text-secondary hover:text-primary">
                  <span class="font-light tracking-tighter text">Log out</span>
              </a>
            <% else %>
              <a href="<%= Routes.user_session_path(@conn, :new) %>" class="px-6 py-3 ml-5 font-bold uppercase link text-secondary hover:text-primary">
                  <span class="font-light tracking-tighter text">Login</span>
              </a>
              <a href="<%= Routes.user_registration_path(@conn, :new) %>" class="px-6 py-3 ml-5 font-bold uppercase link text-secondary hover:text-primary">
                  <span class="font-light tracking-tighter text">Register</span>
              </a>
            <% end %>
          </div>
        </aside>
      <%= @inner_content %>
    </main>
  </body>
  <footer class="bg-blue-100">
    <div class="container px-6 py-12 mx-auto text-center border-t border-gray-300 text-secondary-500">
      <p>Copyright ©2020 MindfullNest. All rights reserved.</p>
    </div>
  </footer>
</html>